version: '3'
services:
  principal_a:
    image: "mongo-start"
    build: ./principal_a
    ports:
      - "27017:27017"
    volumes:
      - ./principal_a/data:/data/db
    depends_on:
      - "secondaire_a_1"
      - "secondaire_a_2"
      - "secondaire_a_3"

  secondaire_a_1:
    image: "mongo"
    build: ./secondaire_a_1
    ports:
      - "27018:27017"
    volumes:
      - ./secondaire_a_1/data:/data/db