version: '3'
services:
  principal_a:
    image: "mongo-start"
    build: ./principal_a
    ports:
      - "27017:27017"
    volumes:
      - ./principal_a/mo
      - ./data/principal_a:/data/db
    command: ["mongod", "--config", "/etc/mongo.conf"]